{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rgwoperator.fullname" . }}
  labels:
    {{- include "rgwoperator.labels" . | nindent 4 }}
data:
    OBJ_ACCESS_KEY_ID: {{ .Values.radosgw.access_key_id | b64enc | quote }}
    OBJ_SECRET_ACCESS_KEY: {{ .Values.radosgw.secret_access_key | b64enc | quote }}
    OBJ_SERVER: {{ .Values.radosgw.server | b64enc | quote }}
{{- end }}