apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buckets.s3.hanse-merkur.de
spec:
  scope: Namespaced
  group: s3.hanse-merkur.de
  names:
    kind: Bucket
    plural: buckets
    singular: bucket
    categories:
      - rgw
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - bucketName
                - ownerAccessKey
              properties:
                bucketName:
                  type: string
                  description: DNS-valid name for the bucket
                ownerAccessKey:
                  type: string
                  description: The AccessKey to link with the bucket
                bucketPolicy:
                  type: string
                  description: Set to policy to private, public or custom for bucket access
                  default: private
                customBucketPolicy:
                  type: string
                  description: AWS S3 compatible bucket policy defining access to the bucket
                lifeCyclePolicy:
                  type: string
                  description: AWS S3 compatible lifecycle policy applied to the bucket objects
                objectVersioning:
                  type: boolean
                  description: Enables object versioning on bucket objects. Use with care
                  default: false
                objectLock:
                  type: boolean
                  description: Stores objects as WORM (Write-Once-Read-Many). Objects can no longer be deleted. This feature cannot be disabled.
                  default: false
                objectLockConfig:
                  type: string
                  description: Custom Object Lock Configuration. Used to retain objects for legally required time due to governance or compliance reasons.
                quotas:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      description: Enables the use of quotas on this bucket
                      default: false
                    maxObjects:
                      type: integer
                      description: The maximum number of objects that can be stored
                      default: -1
                    maxSize:
                      type: integer
                      description: The maximum size in kb of objects that can be stored
                      default: -1
            status:
              type: object
              properties:
                ready:
                  type: boolean
                  default: false
                owner:
                  type: string
                size:
                  type: integer
                objects:
                  type: integer
                maxSize:
                  type: integer
                maxObjects:
                  type: integer
      additionalPrinterColumns:
        - name: Bucket
          type: string
          description: The bucket name in DNS-valid format
          jsonPath: .spec.bucketName
        - name: Owner
          type: string
          description: The contact for this Bucket
          jsonPath: .status.owner
        - name: Ready
          type: boolean
          description: Status of the Bucket
          jsonPath: .status.ready
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp