apiVersion: s3.hanse-merkur.de/v1alpha1
kind: User
metadata:
  name: operator-test
  annotations:
    s3.hanse-merkur.de/allow-deletion: "true"
    s3.hanse-merkur.de/allow-import: "true"
spec:
  userId: operator-test
  contactName: Operator Test
  suspended: false
  quotas:
    enabled: true
    maxObjects: 1000000
    maxSize: 1024000
    maxBuckets: 10
